version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: career_os_backend
    restart: unless-stopped
    ports:
      - "8000:8000" # Consider putting this behind an AWS Application Load Balancer or Nginx
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${BACKEND_SECRET_KEY}
      CORS_ORIGINS: ${FRONTEND_PROD_URL}
    command: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000

  # Frontend Dashboard
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${BACKEND_PROD_URL}
    container_name: career_os_frontend
    restart: unless-stopped
    ports:
      - "3000:3000" # Consider putting this behind an AWS Application Load Balancer or Nginx
    environment:
      NEXT_PUBLIC_API_URL: ${BACKEND_PROD_URL}
    depends_on:
      - backend
